src/Entity/Departements.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\DepartementsRepository")
 */
class Departements
{

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $dep_nom;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $dep_mail;



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDepNom(): ?string
    {
        return $this->dep_nom;
    }

    public function setDepNom(string $dep_nom): self
    {
        $this->dep_nom = $dep_nom;

        return $this;
    }

    public function getDepMail(): ?string
    {
        return $this->dep_mail;
    }

    public function setDepMail(string $dep_mail): self
    {
        $this->dep_mail = $dep_mail;

        return $this;
    }


}

src/Form/DepartementsType.php
<?php

namespace App\Form;

use App\Entity\Departements;
use App\Form\Type\DepartementIdType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DepartementsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('dep_nom')
            ->add('dep_mail')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Departements::class,
        ]);
    }
}

src/Controller/DepartementsController.php
<?php

namespace App\Controller;

use App\Entity\Departements;
use App\Form\DepartementsType;
use App\Repository\DepartementsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/departements")
 */
class DepartementsController extends AbstractController
{
    /**
     * @Route("/", name="departements_index", methods={"GET"})
     */
    public function index(DepartementsRepository $departementsRepository): Response
    {
        return $this->render('departements/index.html.twig', [
            'departements' => $departementsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="departements_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $departement = new Departements();
        $form = $this->createForm(DepartementsType::class, $departement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($departement);
            $entityManager->flush();

            return $this->redirectToRoute('departements_index');
        }

        return $this->render('departements/new.html.twig', [
            'departement' => $departement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="departements_show", methods={"GET"})
     */
    public function show(Departements $departement): Response
    {
        return $this->render('departements/show.html.twig', [
            'departement' => $departement,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="departements_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Departements $departement): Response
    {
        $form = $this->createForm(DepartementsType::class, $departement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('departements_index');
        }

        return $this->render('departements/edit.html.twig', [
            'departement' => $departement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="departements_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Departements $departement): Response
    {
        if ($this->isCsrfTokenValid('delete'.$departement->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($departement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('departements_index');
    }
}

templates/departements/_delete_form.html.twig
<form method="post" action="{{ path('departements_delete', {'id': departement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ departement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/departements/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/departements/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Departements{% endblock %}

{% block body %}
    <h1>Edit Departements</h1>

    {{ include('departements/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('departements_index') }}">back to list</a>

    {{ include('departements/_delete_form.html.twig') }}
{% endblock %}

templates/departements/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Departements index{% endblock %}

{% block body %}
    <h1>Departements index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Dep_nom</th>
                <th>Dep_mail</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for departement in departements %}
            <tr>
                <td>{{ departement.id }}</td>
                <td>{{ departement.depNom }}</td>
                <td>{{ departement.depMail }}</td>
                <td>
                    <a href="{{ path('departements_show', {'id': departement.id}) }}">show</a>
                    <a href="{{ path('departements_edit', {'id': departement.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('departements_new') }}">Create new</a>
{% endblock %}

templates/departements/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Departements{% endblock %}

{% block body %}
    <h1>Create new Departements</h1>

    {{ include('departements/_form.html.twig') }}

    <a href="{{ path('departements_index') }}">back to list</a>
{% endblock %}

templates/departements/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Departements{% endblock %}

{% block body %}
    <h1>Departements</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ departement.id }}</td>
            </tr>
            <tr>
                <th>Dep_nom</th>
                <td>{{ departement.depNom }}</td>
            </tr>
            <tr>
                <th>Dep_mail</th>
                <td>{{ departement.depMail }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('departements_index') }}">back to list</a>

    <a href="{{ path('departements_edit', {'id': departement.id}) }}">edit</a>

    {{ include('departements/_delete_form.html.twig') }}
{% endblock %}